server:
  port: ${PORT:8080}

spring:
  application:
    name: patrimonio
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:patrimonio_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
